{
 "title": "Infpyng - Ping Monitor",
 "description": "【Infpyng】 is a simple python script which utilize fping to probe endpoint through ICMP and parsing the output with Telegraf - Exec Input Plugin to Influxdb",
 "tags": [ "Influx" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"infpyng\" WITH KEY = \"host\""
   },
   {
    "name": "Country",
    "query": "SHOW TAG VALUES FROM \"infpyng\" WITH KEY = \"country\" WHERE \"host\" =~ /$Host/"
   },
   {
    "name": "Server",
    "query": "SHOW TAG VALUES FROM \"infpyng\" WITH KEY = \"server\" WHERE (\"host\" =~ /$Host/ AND \"country\" =~ /^$Country/)"
   },
   {
    "name": "Target",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"infpyng\" WITH KEY = \"target\" WHERE (\"host\" =~ /^$Host/ AND \"country\" =~ /^$Country/ AND \"server\" =~ /^$Server/)"
   }
  ]
 },
 "panels": [
  { "title": "Ping Average", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ping Average Response Time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_target",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT max(\"average_response_ms\") FROM \"infpyng\" WHERE (\"host\" =~ /^$Host$/ AND \"country\" =~ /^$Country$/ AND \"server\" =~ /^$Server$/ AND \"target\" =~ /^$Target$/) AND $timeFilter GROUP BY time($__interval), \"target\" fill(null)",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "plaque", "operator": "=~", "value": "/^$Plaque$/" },
      { "condition": "AND", "key": "equipement", "operator": "=~", "value": "/^$Equipement$/" },
      { "condition": "AND", "key": "url", "operator": "=~", "value": "/^$Target$/" }
     ]
    }
   ]
  },
  { "title": "Packet Loss", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Packet Loss Percentage",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_target",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT max(\"percent_packet_loss\") FROM \"infpyng\" WHERE (\"host\" =~ /^$Host$/ AND \"country\" =~ /^$Country$/ AND \"server\" =~ /^$Server$/ AND \"target\" =~ /^$Target$/) AND $timeFilter GROUP BY time($__interval), \"target\" fill(null)",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "Target Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "$Target",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "repeat": "Target",
   "yaxes": [
    { "format": "ms", "label": "Ping" }
   ],
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"minimum_response_ms\") FROM \"infpyng\" WHERE (\"host\" =~ /^$Host$/ AND \"country\" =~ /^$Country$/ AND \"server\" =~ /^$Server$/ AND \"target\" =~ /^$Target$/) AND $timeFilter GROUP BY time($__interval), \"target\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"average_response_ms\") FROM \"infpyng\" WHERE (\"host\" =~ /^$Host$/ AND \"country\" =~ /^$Country$/ AND \"server\" =~ /^$Server$/ AND \"target\" =~ /^$Target$/) AND $timeFilter GROUP BY time($__interval), \"target\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"maximum_response_ms\") FROM \"infpyng\" WHERE (\"host\" =~ /^$Host$/ AND \"country\" =~ /^$Country$/ AND \"server\" =~ /^$Server$/ AND \"target\" =~ /^$Target$/) AND $timeFilter GROUP BY time($__interval), \"target\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "loss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"percent_packet_loss\") FROM \"infpyng\" WHERE (\"host\" =~ /^$Host$/ AND \"country\" =~ /^$Country$/ AND \"server\" =~ /^$Server$/ AND \"target\" =~ /^$Target$/) AND $timeFilter GROUP BY time($__interval), \"target\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Availability Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "$Target Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 38 },
   "repeat": "Target",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT 100 - mean(\"percent_packet_loss\") FROM \"infpyng\" WHERE (\"host\" =~ /^$Host$/ AND \"country\" =~ /^$Country$/ AND \"server\" =~ /^$Server$/ AND \"target\" =~ /^$Target$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "Ping Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "$Target Ping",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 42 },
   "repeat": "Target",
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT mean(\"average_response_ms\") FROM \"infpyng\" WHERE (\"host\" =~ /^$Host$/ AND \"country\" =~ /^$Country$/ AND \"server\" =~ /^$Server$/ AND \"target\" =~ /^$Target$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  }
 ]
}